# Github Actions Workflow file that builds and pushes the docker images.
name: practicalgitops.app
env:
  DOCKERHUB_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/practicalgitops"
  DOCKERFILE_PATH: app

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "!**/README.md"

# Job declaration starts.
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "${{ env.DOCKERFILE_PATH }}"
          push: true
          tags: "${{ env.DOCKERHUB_TAG }}:latest"
  